# Generated by Django 3.2.3 on 2021-05-31 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='İsim')),
                ('use', models.BooleanField(default=False, verbose_name='Kullan')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'sliderlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SliderImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='path/%Y/%M/%D/')),
                ('slidermodel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blm_image', to='anasayfa.slidermodel')),
            ],
            options={
                'verbose_name': 'bölüm resmi',
                'verbose_name_plural': 'bölüm resimleri',
                'ordering': ['id'],
            },
        ),
    ]
