# Generated by Django 3.2.3 on 2021-05-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HizmetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=4, verbose_name='Başlık')),
                ('mainimage', models.ImageField(null=True, upload_to='', verbose_name='resim "360X215"')),
                ('decription', models.TextField(max_length=170, verbose_name='Açıklama')),
                ('use', models.BooleanField(default=False, verbose_name='Kullan')),
            ],
            options={
                'verbose_name': 'hizmet',
                'verbose_name_plural': 'hizmetler',
                'ordering': ['id'],
            },
        ),
    ]
