# Generated by Django 3.2.3 on 2021-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_hizmetmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slidermodel',
            options={'ordering': ['id'], 'verbose_name': 'Slider', 'verbose_name_plural': 'sliders'},
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Title'),
        ),
    ]
