# Generated by Django 3.2.3 on 2021-05-31 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0003_auto_20210531_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=4, verbose_name='Başlık')),
                ('mainimage', models.ImageField(null=True, upload_to='', verbose_name='logo "165X54"')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='sliderimagemodel',
            name='slidermodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide_image', to='anasayfa.slidermodel'),
        ),
    ]
