# Generated by Django 3.2.3 on 2021-05-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0004_auto_20210531_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidermodel',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='slidermodel',
            name='title',
        ),
        migrations.AddField(
            model_name='sliderimagemodel',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sub Title'),
        ),
        migrations.AddField(
            model_name='sliderimagemodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Title'),
        ),
    ]
