# Generated by Django 3.2.3 on 2021-05-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0005_auto_20210531_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='title',
            field=models.CharField(blank=True, max_length=40, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='hizmetmodel',
            name='title',
            field=models.CharField(blank=True, max_length=40, verbose_name='Başlık'),
        ),
    ]
