# Generated by Django 3.2.3 on 2021-06-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0006_auto_20210531_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientopinionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, verbose_name='Client name')),
                ('company', models.CharField(blank=True, max_length=40, verbose_name='Şirket')),
                ('decription', models.TextField(max_length=170, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'yorumlar',
                'ordering': ['id'],
            },
        ),
    ]
