# Generated by Django 3.2.3 on 2021-06-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0007_clientopinionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hizmetmodel',
            name='decription',
            field=models.TextField(max_length=1700, verbose_name='Açıklama'),
        ),
    ]
