# Generated by Django 3.2.3 on 2021-06-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0008_alter_hizmetmodel_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hizmetmodel',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim "360X215"'),
        ),
    ]
