# Generated by Django 3.2.4 on 2021-07-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0009_alter_hizmetmodel_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientopinionmodel',
            name='decription_en',
            field=models.TextField(blank=True, max_length=170, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='hizmetmodel',
            name='decription_en',
            field=models.TextField(blank=True, max_length=1700, null=True, verbose_name='Açıklama en'),
        ),
        migrations.AddField(
            model_name='hizmetmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Başlık en'),
        ),
        migrations.AddField(
            model_name='sliderimagemodel',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sub Title en'),
        ),
        migrations.AddField(
            model_name='sliderimagemodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Title en'),
        ),
    ]
