# Generated by Django 3.2.4 on 2021-07-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0010_auto_20210707_0118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientModel',
        ),
        migrations.DeleteModel(
            name='HizmetModel',
        ),
        migrations.DeleteModel(
            name='SliderImageModel',
        ),
        migrations.DeleteModel(
            name='SliderModel',
        ),
    ]
