# Generated by Django 3.2.4 on 2021-07-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0011_auto_20210719_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientopinionmodel',
            name='decription',
            field=models.TextField(max_length=400, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='clientopinionmodel',
            name='decription_en',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Açıklama'),
        ),
    ]
