# Generated by Django 3.2.4 on 2021-08-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0012_auto_20210723_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientopinionmodel',
            name='decription_en',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Açıklama_en'),
        ),
    ]
