# Generated by Django 3.2.4 on 2021-10-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0013_alter_clientopinionmodel_decription_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, verbose_name='İsim')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='ana resim "476x595"')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, verbose_name='İsim')),
                ('small', models.CharField(blank=True, max_length=40, verbose_name='light text')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='ana resim "476x595"')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='clientopinionmodel',
            name='decription_en',
        ),
        migrations.AddField(
            model_name='clientopinionmodel',
            name='name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Client name'),
        ),
        migrations.AlterField(
            model_name='clientopinionmodel',
            name='title',
            field=models.CharField(blank=True, max_length=40, verbose_name='Başlık'),
        ),
    ]
