# Generated by Django 3.2.4 on 2021-10-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0014_auto_20211017_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientopinionmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='client  "148x148"'),
        ),
    ]
