# Generated by Django 3.1.1 on 2020-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('closed', 'Closed')], default='new', max_length=6)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='İnfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300, verbose_name='Başlık')),
                ('startedat', models.CharField(max_length=300, verbose_name='Kafe Açılış Saati')),
                ('closedat', models.CharField(max_length=300, verbose_name='Kafe Kapanış Saati')),
                ('email', models.CharField(max_length=300, verbose_name='Email Adresi')),
                ('phone', models.CharField(max_length=300, verbose_name='Telefon Numarası')),
            ],
            options={
                'verbose_name': 'İletişim Bilgileri',
                'verbose_name_plural': 'İletişim Bilgileri',
                'ordering': ['email'],
            },
        ),
    ]
