# Generated by Django 3.2.4 on 2021-06-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='İnfo',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar'},
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
